"use client";

import { useMemo, useState } from "react";
import { Check, CircleAlert, Info, Search, ShieldAlert, X } from "lucide-react";

import { relativeTime } from "@/lib/metrics";
import type { Execution, Incident, IncidentStatus } from "@/lib/types";

export function IncidentsView({ incidents, executions, onStatus, onOpenRun }: { incidents: Incident[]; executions: Execution[]; onStatus: (id: string, status: IncidentStatus) => Promise<unknown>; onOpenRun: (run: Execution) => void }) {
  const [query, setQuery] = useState(""); const [severity, setSeverity] = useState("all"); const [status, setStatus] = useState("all"); const [selectedId, setSelectedId] = useState<string | null>(null);
  const [updating, setUpdating] = useState(false); const [actionError, setActionError] = useState<string | null>(null);
  const filtered = useMemo(() => incidents.filter((incident) => (severity === "all" || incident.severity === severity) && (status === "all" || incident.status === status) && `${incident.title} ${incident.description} ${incident.application} ${incident.traceId}`.toLowerCase().includes(query.toLowerCase())), [incidents, query, severity, status]);
  const selected = incidents.find((incident) => incident.id === selectedId) ?? null;
  const critical = incidents.filter((incident) => incident.severity === "critical" && incident.status !== "resolved").length;
  const warnings = incidents.filter((incident) => incident.severity === "warning" && incident.status !== "resolved").length;
  const info = incidents.filter((incident) => incident.severity === "info" && incident.status !== "resolved").length;
  async function updateStatus(nextStatus: IncidentStatus) {
    if (!selected) return;
    setUpdating(true); setActionError(null);
    try { await onStatus(selected.id, nextStatus); }
    catch (caught) { setActionError((caught as Error).message); }
    finally { setUpdating(false); }
  }
  return <div className="module-view view-enter"><div className="page-intro"><div><h2>Incidents</h2><p>Abnormal activity persisted from runtime policy decisions and execution evidence.</p></div></div>
    <section className="metric-strip incident-metrics"><article><span className="metric-icon charcoal"><CircleAlert size={18} /></span><div><span>Total</span><strong>{incidents.length}</strong><small>{incidents.filter((incident) => incident.status === "open").length} open</small></div></article><article><span className="metric-icon magenta"><ShieldAlert size={18} /></span><div><span>Critical</span><strong>{critical}</strong><small>Immediate review</small></div></article><article><span className="metric-icon cream"><CircleAlert size={18} /></span><div><span>Warning</span><strong>{warnings}</strong><small>Threshold breach</small></div></article><article><span className="metric-icon blue"><Info size={18} /></span><div><span>Info</span><strong>{info}</strong><small>Performance signal</small></div></article></section>
    <section className="panel incident-table-panel"><div className="filterbar"><label className="search-control"><Search size={16} /><input aria-label="Search incidents" placeholder="Incident, application, or trace" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select aria-label="Filter incident severity" value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="all">All severity</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Info</option></select><select aria-label="Filter incident status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All status</option><option value="open">Open</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved</option></select></div><div className="table-scroll"><table><thead><tr><th>Severity</th><th>Type</th><th>Description</th><th>Application</th><th>Trace ID</th><th>Time</th><th>Status</th></tr></thead><tbody>{filtered.map((incident) => <tr key={incident.id} onClick={() => setSelectedId(incident.id)} className="clickable-row"><td><span className="severity-pill" data-severity={incident.severity}>{incident.severity}</span></td><td>{incident.title}</td><td>{incident.description}</td><td>{incident.application}</td><td><button className="trace-link" type="button">{incident.traceId}</button></td><td>{relativeTime(incident.createdAt)}</td><td><span className="incident-status" data-status={incident.status}>{incident.status}</span></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="empty-table">No incidents match these filters.</div>}</div></section>
    {selected && <section className="panel incident-report"><div className="panel-heading"><div><h2>Incident report</h2><p>{selected.traceId}</p></div><button className="icon-button" onClick={() => setSelectedId(null)} title="Close incident report" type="button"><X size={17} /></button></div><div className="report-grid"><dl><div><dt>Type</dt><dd>{selected.title}</dd></div><div><dt>Application</dt><dd>{selected.application}</dd></div><div><dt>Model</dt><dd>{selected.model}</dd></div><div><dt>Created</dt><dd>{new Date(selected.createdAt).toLocaleString()}</dd></div></dl><div><h3>Description</h3><p>{selected.description}</p><h3>Impact</h3><p>{selected.impact}</p><h3>Recommendation</h3><p>{selected.recommendation}</p></div><div><span className="severity-pill" data-severity={selected.severity}>{selected.severity}</span><span className="incident-status" data-status={selected.status}>{selected.status}</span><h3>Evidence</h3>{selected.evidence.map((item) => <code key={item}>{item}</code>)}{actionError && <p className="form-error">{actionError}</p>}<div className="report-actions">{selected.status === "open" && <button className="secondary-button" disabled={updating} onClick={() => void updateStatus("acknowledged")} type="button"><Check size={14} />Acknowledge</button>}<button className="primary-button" disabled={updating || selected.status === "resolved"} onClick={() => void updateStatus("resolved")} type="button">{updating ? "Updating" : "Resolve"}</button><button className="link-button" onClick={() => { const run = executions.find((item) => item.id === selected.executionId); if (run) onOpenRun(run); }} type="button">View trace</button></div></div></div></section>}
  </div>;
}
