import { BellRing, Database, Fingerprint, KeyRound, Radar, Server } from "lucide-react";

import type { ConnectionConfig, ConsoleSettings, DataMode, Health } from "@/lib/types";

export function SettingsView({ mode, connection, health, settings, onUpdate, onConnection }: { mode: DataMode; connection: ConnectionConfig | null; health: Health | null; settings: ConsoleSettings; onUpdate: (patch: Partial<ConsoleSettings>) => void; onConnection: () => void }) {
  const dependencies = Object.entries(health?.dependencies ?? {});
  return <div className="module-view view-enter"><div className="page-intro"><div><h2>Settings</h2><p>Runtime connection, detection thresholds, notifications, retention, and data protection.</p></div></div>
    <div className="settings-grid">
      <section className="panel settings-panel"><div className="settings-title"><Server size={19} /><div><h3>Control API</h3><p>Execution and workspace data source</p></div></div><dl className="setting-rows"><div><dt>Mode</dt><dd><span className="mode-badge" data-mode={mode}>{mode}</span></dd></div><div><dt>Base URL</dt><dd><code>{connection?.apiUrl ?? "Not connected"}</code></dd></div><div><dt>Refresh</dt><dd>15 seconds</dd></div></dl><button className="secondary-button" onClick={onConnection} type="button"><KeyRound size={15} />Manage API</button></section>
      <section className="panel settings-panel"><div className="settings-title"><Database size={19} /><div><h3>Dependencies</h3><p>Reported by the health endpoint</p></div></div>{dependencies.length ? <div className="dependency-list">{dependencies.map(([name, value]) => <div key={name}><i data-state={value.status} /><strong>{name}</strong><span>{value.status}</span><small>{value.detail ?? "Connected"}</small></div>)}</div> : <div className="empty-state compact"><strong>No live probe</strong><span>Connect the API to load PostgreSQL and Redis health.</span></div>}</section>
      <section className="panel settings-panel wide"><div className="settings-title"><Radar size={19} /><div><h3>Risk review</h3><p>Browser preferences for execution risk labels; server incidents use runtime policies.</p></div></div><div className="numeric-settings"><label><span>Loop repeats</span><input min="2" max="20" type="number" value={settings.repeatThreshold} onChange={(event) => onUpdate({ repeatThreshold: Number(event.target.value) })} /><small>Critical review begins after this count</small></label><label><span>High tokens</span><input min="1000" step="1000" type="number" value={settings.highTokenThreshold} onChange={(event) => onUpdate({ highTokenThreshold: Number(event.target.value) })} /><small>Single-execution review threshold</small></label><label><span>Slow run</span><input min="1000" step="500" type="number" value={settings.slowRunThresholdMs} onChange={(event) => onUpdate({ slowRunThresholdMs: Number(event.target.value) })} /><small>End-to-end review threshold</small></label></div></section>
      <section className="panel settings-panel"><div className="settings-title"><BellRing size={19} /><div><h3>Notifications</h3><p>Controls the topbar incident count</p></div></div><div className="toggle-list"><label><span><strong>Critical</strong><small>Blocked loops and failed routes</small></span><input checked={settings.notifyCritical} onChange={(event) => onUpdate({ notifyCritical: event.target.checked })} type="checkbox" /></label><label><span><strong>Warnings</strong><small>Usage and latency thresholds</small></span><input checked={settings.notifyWarnings} onChange={(event) => onUpdate({ notifyWarnings: event.target.checked })} type="checkbox" /></label></div></section>
      <section className="panel settings-panel"><div className="settings-title"><Fingerprint size={19} /><div><h3>Data protection</h3><p>Prompt content remains disabled</p></div></div><div className="privacy-list"><div><span>Prompt storage</span><strong>Off</strong></div><div><span>Fingerprints</span><strong>On</strong></div><label><span>Retention days</span><input min="1" max="90" type="number" value={settings.retentionDays} onChange={(event) => onUpdate({ retentionDays: Number(event.target.value) })} /></label><p>Retention is a dashboard preference until a cleanup worker is connected. The project credential remains in memory and is discarded on reload.</p></div></section>
    </div>
  </div>;
}
